In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

C:\Users\dhruv\AppData\Local\Temp\ipykernel_39264\2906776592.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [7]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [8]:
books.duplicated().sum()

0

In [9]:
users.duplicated().sum()

0

In [10]:
ratings.duplicated().sum()

0

# POPULARITY BASED RECOMMENDATION SYSTEM

In [11]:
ratings_with_name = ratings.merge(books,on="ISBN")
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [12]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num-ratings'},inplace=True)
num_rating_df

                                               Book-Title  num-ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [13]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean(['Book-Rating']).reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg-ratings'},inplace=True)
avg_rating_df

,Book-Title,User-ID,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,51807.250000,2.250000
1,Always Have Popsicles,172742.000000,0.000000
2,Apple Magic (The Collector's series),198711.000000,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",269557.000000,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,11601.000000,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,100532.500000,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,116729.500000,5.250000
241068,Ã?Â?sterlich leben.,256636.000000,7.000000
241069,Ã?Â?stlich der Berge.,198497.333333,2.666667
241070,Ã?Â?thique en toc,39532.000000,4.000000

In [14]:
popular_books = num_rating_df.merge(avg_rating_df,on='Book-Title').drop(columns=['User-ID'])
popular_books

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [15]:
popular_books = popular_books[popular_books['num-ratings']>=400].sort_values('avg-ratings',ascending=False).head(20)

In [16]:
popular_books

,Book-Title,num-ratings,avg-ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
206502,The Secret Life of Bees,774,4.447028
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
107962,Life of Pi,664,4.088855
76343,Good in Bed,490,4.055102
170101,Suzanne's Diary for Nicholas,457,3.820569
5664,A Prayer for Owen Meany,413,3.796610
118237,Me Talk Pretty One Day,457,3.752735
219349,Timeline,552,3.750000

In [17]:
popular_books = popular_books.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Year-Of-Publication','Image-URL-M','num-ratings','avg-ratings']]

In [18]:
popular_books

,Book-Title,Book-Author,Year-Of-Publication,Image-URL-M,num-ratings,avg-ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
6,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
8,To Kill a Mockingbird,Harper Lee,1988,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
16,The Da Vinci Code,Dan Brown,2003,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
22,The Five People You Meet in Heaven,Mitch Albom,2003,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
24,The Catcher in the Rye,J.D. Salinger,1991,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
31,The Lovely Bones: A Novel,Alice Sebold,2002,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
32,The Secret Life of Bees,Sue Monk Kidd,2003,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
38,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
41,The Red Tent (Bestselling Backlist),Anita Diamant,1998,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
42,Fahrenheit 451,Ray Bradbury,1994,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
55,Girl with a Pearl Earring,Tracy Chevalier,2001,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
56,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
57,Life of Pi,Yann Martel,2002,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
61,Good in Bed,Jennifer Weiner,2002,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
63,Suzanne's Diary for Nicholas,James Patterson,2001,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
67,A Prayer for Owen Meany,John Irving,1990,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
69,Me Talk Pretty One Day,David Sedaris,2001,http://images.amazon.com/images/P/0316776963.0...,457,3.752735
73,Timeline,MICHAEL CRICHTON,2000,http://images.amazon.com/images/P/0345417623.0...,552,3.750000

# COLLABORATIVE FILTERING BASED RECOMMENDATION SYSTEM

In [19]:
a = ratings_with_name.groupby('User-ID').count()['Book-Rating']>100
rated_users = a[a].index

In [20]:
filtered_ratings = ratings_with_name[ratings_with_name['User-ID'].isin(rated_users)]
filtered_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
14,77480,034545104X,8,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031115,276680,0812881311,0,Streets of Gold,Evan Hunter,1985,Madison Books,http://images.amazon.com/images/P/0812881311.0...,http://images.amazon.com/images/P/0812881311.0...,http://images.amazon.com/images/P/0812881311.0...
1031116,276680,0865055041,0,Kitchen (Historic Communities (Paperback)),Bobbie Kalman,1990,Crabtree Publishing Company,http://images.amazon.com/images/P/0865055041.0...,http://images.amazon.com/images/P/0865055041.0...,http://images.amazon.com/images/P/0865055041.0...
1031117,276680,086505505X,0,Home Crafts (Historic Communities (Paperback)),Bobbie Kalman,1990,Crabtree Publishing Company,http://images.amazon.com/images/P/086505505X.0...,http://images.amazon.com/images/P/086505505X.0...,http://images.amazon.com/images/P/086505505X.0...
1031118,276680,1564407284,0,"The Old Sturbridge Village Cookbook, 2nd : Aut...",Caroline Sloat,1995,Globe Pequot,http://images.amazon.com/images/P/1564407284.0...,http://images.amazon.com/images/P/1564407284.0...,http://images.amazon.com/images/P/1564407284.0...
1031119,276680,1582343594,0,City of Masks : A Cree Black Novel,Daniel Hecht,2004,Bloomsbury USA,http://images.amazon.com/images/P/1582343594.0...,http://images.amazon.com/images/P/1582343594.0...,http://images.amazon.com/images/P/1582343594.0...

In [21]:
y = filtered_ratings.groupby('Book-Title').count()['Book-Rating']>=20
famous_books = y[y].index

In [22]:
final_ratings = filtered_ratings[filtered_ratings['Book-Title'].isin(famous_books)]

In [23]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [24]:
pt.fillna(0,inplace=True)

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity_score = cosine_similarity(pt)

In [27]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    simialar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1], reverse=True)[1:11]

    data=[]
    for i in simialar_items:
        item=[]
        print(pt.index[i[0]])
        temp_df = books[books['Book-Title']==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

        data.append(item)
    return data

In [28]:
test = final_ratings.drop_duplicates('Book-Title')[['ISBN','Book-Rating','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-M']]
test

,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
2,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
63,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
184,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...
368,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...
506,0449006522,8,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...
...,...,...,...,...,...,...,...
759460,0140430105,0,Emma (Penguin Classics),Jane Austen,1966,Penguin Books,http://images.amazon.com/images/P/0140430105.0...
764025,155166948X,0,Prince Joe,Suzanne Brockmann,2002,Mira,http://images.amazon.com/images/P/155166948X.0...
785009,1551667428,0,After Midnight,Diana Palmer,2003,Mira Books,http://images.amazon.com/images/P/1551667428.0...
785647,0440241111,7,Slightly Scandalous (Get Connected Romances),Mary Balogh,2003,Dell Publishing Company,http://images.amazon.com/images/P/0440241111.0...
794037,0671737635,0,Something Wonderful,Judith McNaught,1991,Pocket,http://images.amazon.com/images/P/0671737635.0...

In [29]:
recommend('Manhattan Hunt Club')

Ice (Shooting Stars)
Sleepwalk
High Crimes
Mary Anne Saves the Day (Baby-Sitters Club, 4)
Summer of Storms
The Unloved
Midnight Voices
Cold Paradise (Stone Barrington Novels (Paperback))
Middle of Nowhere
The Pledge

[['Ice (Shooting Stars)',
  'V.C. Andrews',
  'http://images.amazon.com/images/P/0671039946.01.MZZZZZZZ.jpg'],
 ['Sleepwalk',
  'John Saul',
  'http://images.amazon.com/images/P/0553288342.01.MZZZZZZZ.jpg'],
 ['High Crimes',
  'Joseph Finder',
  'http://images.amazon.com/images/P/0688149626.01.MZZZZZZZ.jpg'],
 ['Mary Anne Saves the Day (Baby-Sitters Club, 4)',
  'Ann M. Martin',
  'http://images.amazon.com/images/P/0590251597.01.MZZZZZZZ.jpg'],
 ['Summer of Storms',
  'Judith Kelman',
  'http://images.amazon.com/images/P/051513290X.01.MZZZZZZZ.jpg'],
 ['The Unloved',
  'John Saul',
  'http://images.amazon.com/images/P/0553272616.01.MZZZZZZZ.jpg'],
 ['Midnight Voices',
  'JOHN SAUL',
  'http://images.amazon.com/images/P/0449006530.01.MZZZZZZZ.jpg'],
 ['Cold Paradise (Stone Barrington Novels (Paperback))',
  'Stuart Woods',
  'http://images.amazon.com/images/P/0451205626.01.MZZZZZZZ.jpg'],
 ['Middle of Nowhere',
  'Ridley Pearson',
  'http://images.amazon.com/images/P/0786889608.01.MZZZZZZZ.jpg'],
 ['The Pledge',
  'Rob Kean',
  'http://images.amazon.com/images/P/0446608483.01.MZZZZZZZ.jpg']]

In [30]:
recommend("16 Lighthouse Road")

Night Shadow
Hurricane Bay
Obsession
Imitation in Death (Eve Dallas Mysteries (Paperback))
The Morning After
Tapestry
A Kiss to Remember
On a Wild Night (Cynster Novels)
Scrooge Wore Spurs
Wild Orchids : A Novel

[['Night Shadow',
  'Catherine Coulter',
  'http://images.amazon.com/images/P/0380756218.01.MZZZZZZZ.jpg'],
 ['Hurricane Bay',
  'Heather Graham',
  'http://images.amazon.com/images/P/1551666650.01.MZZZZZZZ.jpg'],
 ['Obsession',
  'Lori Herter',
  'http://images.amazon.com/images/P/0425128172.01.MZZZZZZZ.jpg'],
 ['Imitation in Death (Eve Dallas Mysteries (Paperback))',
  'J. D. Robb',
  'http://images.amazon.com/images/P/0425191583.01.MZZZZZZZ.jpg'],
 ['The Morning After',
  'Lisa Jackson',
  'http://images.amazon.com/images/P/0821772953.01.MZZZZZZZ.jpg'],
 ['Tapestry',
  'Lynn Kurland',
  'http://images.amazon.com/images/P/0515133620.01.MZZZZZZZ.jpg'],
 ['A Kiss to Remember',
  'TERESA MEDEIROS',
  'http://images.amazon.com/images/P/0553581856.01.MZZZZZZZ.jpg'],
 ['On a Wild Night (Cynster Novels)',
  'Stephanie Laurens',
  'http://images.amazon.com/images/P/0380812037.01.MZZZZZZZ.jpg'],
 ['Scrooge Wore Spurs',
  'Janet Dailey',
  'http://images.amazon.com/images/P/0821772252.01.MZZZZZZZ.jpg'],
 ['Wild Orchids : A Novel',
  'Jude Deveraux',
  'http://images.amazon.com/images/P/0743437136.01.MZZZZZZZ.jpg']]

In [31]:
recommend('1984')

Animal Farm
Lying Awake
Waiting
Written on the Body
Brave New World
The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))
Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death
The Mysteries of Pittsburgh
Sarah's Window
American Pastoral

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ['Lying Awake',
  'Mark Salzman',
  'http://images.amazon.com/images/P/0375406328.01.MZZZZZZZ.jpg'],
 ['Waiting',
  'Frank M. Robinson',
  'http://images.amazon.com/images/P/0812541642.01.MZZZZZZZ.jpg'],
 ['Written on the Body',
  'Jeanette Winterson',
  'http://images.amazon.com/images/P/0679744479.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ["The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))",
  'Douglas Adams',
  'http://images.amazon.com/images/P/0345391810.01.MZZZZZZZ.jpg'],
 ["Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
  'Kurt Vonnegut',
  'http://images.amazon.com/images/P/0440180295.01.MZZZZZZZ.jpg'],
 ['The Mysteries of Pittsburgh',
  'Michael Chabon',
  'http://images.amazon.com/images/P/0060972122.01.MZZZZZZZ.jpg'],
 ["Sarah's Window",
  'Janice Graham',
  'http://images.amazon.com/images/P/0399146296.01.MZZZZZZZ.jpg'],
 ['American Pastoral',
  'Philip Roth',
  'http://images.amazon.com/images/P/0375701427.01.MZZZZZZZ.jpg']]

import pickle
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_scores.pkl','wb')) 
pickle.dump(test,open('test.pkl','wb'))
pickle.dump(avg_rating_df,open('avg_rating_df','wb'))

In [32]:
filtered_ratings.drop_duplicates('Book-Title')

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...,http://images.amazon.com/images/P/038550120X.0...
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
506,11676,0449006522,8,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...,http://images.amazon.com/images/P/0449006522.0...
...,...,...,...,...,...,...,...,...,...,...
1031115,276680,0812881311,0,Streets of Gold,Evan Hunter,1985,Madison Books,http://images.amazon.com/images/P/0812881311.0...,http://images.amazon.com/images/P/0812881311.0...,http://images.amazon.com/images/P/0812881311.0...
1031116,276680,0865055041,0,Kitchen (Historic Communities (Paperback)),Bobbie Kalman,1990,Crabtree Publishing Company,http://images.amazon.com/images/P/0865055041.0...,http://images.amazon.com/images/P/0865055041.0...,http://images.amazon.com/images/P/0865055041.0...
1031117,276680,086505505X,0,Home Crafts (Historic Communities (Paperback)),Bobbie Kalman,1990,Crabtree Publishing Company,http://images.amazon.com/images/P/086505505X.0...,http://images.amazon.com/images/P/086505505X.0...,http://images.amazon.com/images/P/086505505X.0...
1031118,276680,1564407284,0,"The Old Sturbridge Village Cookbook, 2nd : Aut...",Caroline Sloat,1995,Globe Pequot,http://images.amazon.com/images/P/1564407284.0...,http://images.amazon.com/images/P/1564407284.0...,http://images.amazon.com/images/P/1564407284.0...
1031119,276680,1582343594,0,City of Masks : A Cree Black Novel,Daniel Hecht,2004,Bloomsbury USA,http://images.amazon.com/images/P/1582343594.0...,http://images.amazon.com/images/P/1582343594.0...,http://images.amazon.com/images/P/1582343594.0...

In [51]:
mostrated = num_rating_df.merge(avg_rating_df,on='Book-Title').drop(columns=['User-ID'])
mostrated[mostrated['num-ratings']>=400].sort_values('avg-ratings',ascending=False).head(20)

,Book-Title,num-ratings,avg-ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
206502,The Secret Life of Bees,774,4.447028
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
107962,Life of Pi,664,4.088855
76343,Good in Bed,490,4.055102
170101,Suzanne's Diary for Nicholas,457,3.820569
5664,A Prayer for Owen Meany,413,3.796610
118237,Me Talk Pretty One Day,457,3.752735
219349,Timeline,552,3.750000